// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/footer/footer.vue')['default']
    NumberDisplay: typeof import('./src/components/NumberDisplay.vue')['default']
    NumberSubmit: typeof import('./src/components/NumberSubmit.vue')['default']
    NutBacktop: typeof import('@nutui/nutui-taro')['Backtop']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
